# Generated by Django 2.2 on 2019-04-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='genero')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='monto')),
                ('autorizado', models.BooleanField(blank=True, default=False, verbose_name='autorizado')),
                ('borrado', models.BooleanField(blank=True, default=False, verbose_name='borrado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha última modificación')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-fecha', 'apellido', 'nombre'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
